name: MMRotator
main: com.minemee.MMRotator.MMRotator
version: 1.0
description: >
             Rotates stairs.
commands:
   rotateon:
      description: Activates the rotator tool.
      usage: /rotateon
      permission: MMRotator.rotateon
      permission-message: You don't have permission.
   rotateoff:
      description: Deactivates the rotator tool.
      usage: /rotateoff
      permission: MMRotator.rotateoff
      permission-message: You don't have permission.
   rotateselect:
      description: Activates the selection tool.
      usage: /rotateselect
      permission: MMRotator.rotateselect
      permission-message: You don't have permission.
permissions:
   MMRotator.*:
       description: Gives access to MMRotator.
       children:
           MMRotator.rotateon: true
           MMRotator.rotateoff: true
   MMRotator.rotateon:
       description: Allows activation of Rotator Tool.
       default: true
   MMRotator.rotateoff:
       description: Allows deactivation of Rotator Tool.
       default: true
   MMRotator.rotateselect:
       description: Allows activation of Selection Tool.
       default: true